#!/bin/sh
##############################################
# Just a little trick...
  eval 'exec photoalbum_generator -f $0 -a izland.txt -A NG_Style -S NG_Style_v2 -c 5 -e ${1+"$@"}'
##############################################
#
# Album
#
# Created: 2005.09.30.
#
# Global overwriting
# overwrite:	[{{STYLE}}=>file:css/NG_Style.CSS]
#
#############################################################################################################################
# Title: Izland 2003102X
#############################################################################################################################
#
# The structure:
# filename|albumbodytheme|slidetheme|backgroundtheme|frametheme
#
#############################################################################################################################

pics/CS2003102D_01411.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2_tooltip[resize();;=>fullsize=1;]|NG_Style_v2_noText|
pics/CS2003102D_01443.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2_tooltip[resize();;=>fullsize=1;]|NG_Style_v2_noText|

#############################################################################################################################
#
### _END_OF_FILE ###
