#!/bin/sh
#
##############################################
# Just a little trick...
  eval 'exec photoalbum_generator -f $0 -A Empty -c 3 -s 0 -w 10 -e ${1+"$@"}'
##############################################
#
# The structure:
# filename|albumbodytheme|slidetheme|backgroundtheme|frametheme
#
#############################################################################################################################

pics/1.jpg|Empty|Empty[GEOMETRY=>asasas]|NG_Style_v2_tooltip|NG_Style_v2_noText_EXIF|
pics/2.jpg|Empty[NOLINK=>YES]|Empty|NG_Style_v2|NG_Style_v2|
pics/3.jpg|Empty[PICTEXT=>t]|Empty|NG_Style_v2|NG_Style_v2|

    pics/1.jpg|Empty|Empty|NG_Style_v2|NG_Style_v2|
    pics/2.jpg|Empty[NOLINK=>YES]|Empty|NG_Style_v2|NG_Style_v2|
    pics/3.jpg|Empty|Empty|NG_Style_v2|NG_Style_v2|

    pics/1.jpg|Empty|Empty|NG_Style_v2|NG_Style_v2|
    pics/2.jpg|Empty[NOLINK=>YES]|Empty|NG_Style_v2|NG_Style_v2|
    pics/3.jpg|Empty|Empty|NG_Style_v2|NG_Style_v2|

#############################################################################################################################
#
### _END_OF_FILE ###
