#!/bin/sh
##############################################
# Just a little trick...
  eval 'exec photoalbum_generator -f $0 -a schneider.txt -A NG_Style -S NG_Style_v2 -c 5 ${1+"$@"}'
##############################################
#
# Album
#
# Created: 2005.04.03.
#
# Global overwriting
# overwrite:	[{{STYLE}}=>file:css/NG_Style.CSS]
#
#############################################################################################################################
# Title: B2005Q2
#############################################################################################################################
#
# The structure:
# filename|albumbodytheme|slidetheme|backgroundtheme|frametheme
#
#############################################################################################################################

#
pics/KM20050406_00661.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2_tooltip|NG_Style_v2_noText_EXIF|
pics/KM20050406_00660.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2_tooltip|NG_Style_v2_noText_EXIF|
pics/KM20050406_00659.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2_tooltip|NG_Style_v2_noText_EXIF|
pics/KM20050406_00656.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2_tooltip|NG_Style_v2_noText_EXIF|

#############################################################################################################################
#
### _END_OF_FILE ###
