#!/bin/sh
##############################################
# Just a little trick...
  eval 'exec photoalbum_generator -f $0 -a budapest.txt -A NG_Style -S NG_Style_v2 -c 5 -e  ${1+"$@"}'
##############################################
#
# Album
#
# Created: 2004.12.31.
#
# Global overwriting
# overwrite:	[{{STYLE}}=>file:css/NG_Style.CSS]
#
#############################################################################################################################
# Title: Budapest
#############################################################################################################################
#
# The structure:
# filename|albumbodytheme|slidetheme|backgroundtheme|frametheme
#
#############################################################################################################################

pics/KM20050323_00291_r.jpg|0[MAXCOL=>4]|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2_tooltip|NG_Style_v2_noText_EXIF|
pics/PICT0009_resized.jpg|0[MAXCOL=>4]|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2_tooltip|NG_Style_v2_noText|

#############################################################################################################################
#
### _END_OF_FILE ###

