#!/bin/sh
#
##############################################
# Just a little trick...
  eval 'exec photoalbum_generator -f $0 -a jamesburke.txt -A NG_Style -S NG_Style_v2 -c 1 ${1+"$@"}'
##############################################
#
# Album
#
# Created: 2005.05.25.
#
# Global overwriting
# overwrite:	[{{STYLE}}=>file:css/NG_Style.CSS]
#
#############################################################################################################################
# Title: James BURKE - 
#############################################################################################################################
#
# The structure:
# filename|albumbodytheme|slidetheme|backgroundtheme|frametheme
#
#############################################################################################################################

#
pics/01.jpg|Blog_Justify[NOLINK=>YES]|NoFrame[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2|
pics/02.jpg|Blog_Justify[NOLINK=>YES]|NoFrame[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2|
pics/03.jpg|Blog_Justify[NOLINK=>YES]|NoFrame[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2|
pics/04.jpg|Blog_Justify[NOLINK=>YES]|NoFrame[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2|
pics/05.jpg|Blog_Justify[NOLINK=>YES]|NoFrame[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2|
pics/06.jpg|Blog_Justify[NOLINK=>YES]|NoFrame[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2|
pics/07.jpg|Blog_Justify[NOLINK=>YES]|NoFrame[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2|
pics/08.jpg|Blog_Justify[NOLINK=>YES]|NoFrame[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2|
pics/09.jpg|Blog_Justify[NOLINK=>YES]|NoFrame[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2|
pics/10.jpg|Blog_Justify[NOLINK=>YES]|NoFrame[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2|

#############################################################################################################################
#
### _END_OF_FILE ###

