#!/bin/sh
#
##############################################
# Just a little trick...
  eval 'exec photoalbum_generator -f $0 -a 20050524.txt -A NG_Style -S NG_Style_v2 -c 5 -e ${1+"$@"}'
##############################################
#
# Album
#
# Created: 2006.06.xx.
#
# Global overwriting
# overwrite:	[{{STYLE}}=>file:css/NG_Style.CSS]
#
#############################################################################################################################
# Title: Villámlátogatás a SOTE-torony tetejére
#############################################################################################################################
#
# The structure:
# filename|albumbodytheme|slidetheme|backgroundtheme|frametheme
#
#############################################################################################################################

pics/KM20060630_05747_HDR.jpg|0[{{TITLE}}=>]|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2_tooltip[resize();;=>fullsize=1;]|NG_Style_v2_borderv2[class="photo"=>border="0",<b>{{TITLE}}</b><br>=>,cellspacing="10"=>]|

pics/KM20060630_05752.jpg|0[{{TITLE}}=>]|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2_tooltip[resize();;=>fullsize=1;]|NG_Style_v2_borderv2[class="photo"=>border="0",<b>{{TITLE}}</b><br>=>,cellspacing="10"=>]|
pics/KM20060630_05755_HDR.jpg|0[{{TITLE}}=>]|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2_tooltip[resize();;=>fullsize=1;]|NG_Style_v2_borderv2[class="photo"=>border="0",<b>{{TITLE}}</b><br>=>,cellspacing="10"=>]|
pics/KM20060630_05775.jpg|0[{{TITLE}}=>]|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2_tooltip[resize();;=>fullsize=1;]|NG_Style_v2_borderv2[class="photo"=>border="0",<b>{{TITLE}}</b><br>=>,cellspacing="10"=>]|
pics/KM20060630_05776.jpg|0[{{TITLE}}=>]|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2_tooltip[resize();;=>fullsize=1;]|NG_Style_v2_borderv2[class="photo"=>border="0",<b>{{TITLE}}</b><br>=>,cellspacing="10"=>]|

pics/KM20060630_05784.jpg|0[{{TITLE}}=>]|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2_tooltip[resize();;=>fullsize=1;]|NG_Style_v2_borderv2[class="photo"=>border="0",<b>{{TITLE}}</b><br>=>,cellspacing="10"=>]|
pics/KM20060630_05788.jpg|0[{{TITLE}}=>]|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2_tooltip[resize();;=>fullsize=1;]|NG_Style_v2_borderv2[class="photo"=>border="0",<b>{{TITLE}}</b><br>=>,cellspacing="10"=>]|

pics/NO20060630_00142.jpg|0[{{TITLE}}=>]|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2_tooltip[resize();;=>fullsize=1;]|NG_Style_v2_borderv2[class="photo"=>border="0",<b>{{TITLE}}</b><br>=>,cellspacing="10"=>]|
pics/NO20060630_00141.jpg|0[{{TITLE}}=>]|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2_tooltip[resize();;=>fullsize=1;]|NG_Style_v2_borderv2[class="photo"=>border="0",<b>{{TITLE}}</b><br>=>,cellspacing="10"=>]|

#############################################################################################################################
#
### _END_OF_FILE ###

