#!/bin/sh
#
##############################################
# Just a little trick...
  eval 'exec photoalbum_generator -f $0 -a 20050507.txt -A NG_Style -S NG_Style_v2 -c 5 ${1+"$@"}'
##############################################
#
# Album
#
# Created: 2004.12.31.
#
# Global overwriting
# overwrite:	[{{STYLE}}=>file:css/NG_Style.CSS]
#
#############################################################################################################################
# Title: Szandra ballagása 2005 05 07
#############################################################################################################################
#
# The structure:
# filename|albumbodytheme|slidetheme|backgroundtheme|frametheme
#
#############################################################################################################################

#
pics/KM20050507_01309.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050507_01310.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050507_01311.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050507_01312.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050507_01313.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050507_01314.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050507_01315.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050507_01316.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050507_01317.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050507_01318.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050507_01319.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050507_01320.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050507_01321.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050507_01322.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050507_01323.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050507_01324.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050507_01325.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050507_01326.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050507_01327.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|

#############################################################################################################################
#
### _END_OF_FILE ###

