#!/bin/sh
#
##############################################
# Just a little trick...
  eval 'exec photoalbum_generator -f $0 -a 20050804.txt -A NG_Style -S NG_Style_v2 -c 5 ${1+"$@"}'
##############################################
#
# Album
#
# Created: 2005.05.25.
#
# Global overwriting
# overwrite:	[{{STYLE}}=>file:css/NG_Style.CSS]
#
#############################################################################################################################
# Title: Enikõ 2005 08 04
#############################################################################################################################
#
# The structure:
# filename|albumbodytheme|slidetheme|backgroundtheme|frametheme
#
#############################################################################################################################

#
pics/KM20050804_03032.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050804_03035.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050804_03036.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050804_03037.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050804_03038.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050804_03039.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050804_03042.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050804_03053.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050804_03054.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050804_03055.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|
pics/KM20050804_03056.jpg|0|0[#FFFFFF=>#3d3d3d,#000001=>#5d5d5d,#000000=>#9d9d9d]|NG_Style_v2|NG_Style_v2_noText|

#############################################################################################################################
#
### _END_OF_FILE ###

